// export { default as rangesService } from "./ranges.service"
// export { default as classesService } from "./classes.service"
// export { default as clubsService } from "./clubs.service"
// export { default as clubsMembersService } from "./clubs.members.service"
// export { default as eventsService } from "./events.service"
export { default as eventsParticipantsService } from "./events.participants.service"
export { default as eventsParticipantsWeaponsService } from "./events.participants.weapons.service"
export { default as eventsDivisionsService } from "./events.divisions.service"
export { default as eventsContestantsService } from "./events.contestants.service"
export { default as eventsContestantsResultsService } from "./events.contestants.results.service"
